dynaconf_merge: true
default:
  NAME: user_service
  HOST: 0.0.0.0
  PORT: 8001
  FAST_API_PATH: src.application.app:user_service
  LOG_LEVEL: info
  RELOADED: True
  REPEAT_TIMEOUT: 3600
  HIGH_LOAD: False
  POSTGRES:
    dialect: asyncpg
    host: localhost
    port: 5432
    login: postgres
    password: postgres
    database: auth_service
    pgbouncer: False
    echo: False
    pool_min_size: 10
    pool_max_size: 20
    pool_timeout: 90
    mat_view_time: 15
  CLICKHOUSE:
    host: localhost
    port: 8122
    user: clickhouse
    password: clickhouse
    database: auth_service
    TYPES:
      INTEGER: Int32
      STRING: String
      VARCHAR: String
      VARCHAR(20): String
      VARCHAR(30): String
      VARCHAR(50): String
      UUID: UUID
      TEXT: String
      DATETIME: DateTime
      FLOAT: Float32
      BOOLEAN: UInt8
  AUTH:
    secret: 666ril_oasis_putin_1488_666
    expiration: 3600
    iterations: 1000
    hash_name: sha256
    formats: utf-8
    algorythm: HS256
    api_x_key_header: 1488_X_ACCESS_X_1488
  USERS:
    guest_role_uuid: ceed0333-c801-479a-aec5-c9abfbf7cf7d
    author_role_uuid: 922fe1ff-dfc9-4f0e-886d-5855882e9c01
    admin_role_uuid: e5c15e78-d655-41c6-86db-01f82da18b02
    moderator_role_uuid: ff32f557-c46f-47e1-8db2-11d638363ae1
    superuser_roles: [ admin ]
    create_permission_uuid: e5c15e78-d655-41c6-86db-01f82da18b02
    read_permission_uuid: 4f0411fd-436e-45c4-b5da-c47062497a15
    update_permission_uuid: f5cbb76c-ed5a-4987-81da-b889bafcee3e
    delete_permission_uuid: 72a92f09-0454-49b2-aca1-f7aa4e2cc8d7
    default_superuser:
      login: admin
      password: admin
      email: admin@email.com
      phone_number: 89996661488
  REDIS:
    host: localhost
    port: 6379
    username:
    password:
    db: 0
  KAFKA:
    routing_key: create_user
    host: localhost
    port: 9092
    acks: all
    transactional_id: d048790b-5c7a-4ec4-9170-be56ac3cfdac
    topics:
      register_topic: auth_service.registration
